version: 2.1

executors:
  global-executor:
    docker:
      - image: circleci/node:10.15.2
    working_directory: ~/datashare-plugin-tour

commands:
  checkout-and-install:
    description: "A command to checkout and install the packages"
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages- # used if checksum fails
      - run:
          name: Install yarn dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save yarn package cache
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}

jobs:
  release:
    executor: global-executor
    steps:
      - checkout-and-install
      - run:
          name: Make distribution
          command: yarn build
      - run:
          name: Release on Github
          command: |
            cd ~/datashare-plugin-tour
            mkdir datashare-plugin-tour-${CIRCLE_TAG}
            cp package.json datashare-plugin-tour-${CIRCLE_TAG}
            cp -R dist datashare-plugin-tour-${CIRCLE_TAG}
            tar czf datashare-plugin-tour-${CIRCLE_TAG}.tgz datashare-plugin-tour-${CIRCLE_TAG}
            zip -r datashare-plugin-tour-${CIRCLE_TAG}.zip datashare-plugin-tour-${CIRCLE_TAG}
            upload_url=$(curl -X POST -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" -d "{\"tag_name\":\"${CIRCLE_TAG}\", \"name\":\"${CIRCLE_TAG}\",\"body\":\"release ${CIRCLE_TAG}\"}" "https://api.github.com/repos/ICIJ/datashare-plugin-tour/releases" | jq -r '.upload_url')
            upload_url="${upload_url%\{*}"
            echo "Uploading asset to release url: $upload_url"
            zip_content_length=$(stat -c%s "datashare-plugin-tour-${CIRCLE_TAG}.zip")
            tar_content_length=$(stat -c%s "datashare-plugin-dattouraconnect-${CIRCLE_TAG}.tgz")
            curl -X POST -s -m 120 -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/zip" -H "Content-Length: $zip_content_length" --data-binary "@datashare-plugin-tour-${CIRCLE_TAG}.zip" "$upload_url?name=datashare-plugin-tour-${CIRCLE_TAG}.zip&label=datashare-plugin-tour-${CIRCLE_TAG}.zip"
            curl -X POST -s -m 120 -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/gzip" -H "Content-Length: $tar_content_length" --data-binary "@datashare-plugin-tour-${CIRCLE_TAG}.tgz" "$upload_url?name=datashare-plugin-tour-${CIRCLE_TAG}.tgz&label=datashare-plugin-tour-${CIRCLE_TAG}.tgz"

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^[0-9.]*/
            branches:
              ignore: /.*/
